// export const ACTIVITY_TYPES = {
//   LEAD_CREATED: "LEAD_CREATED",
//   LEAD_UPDATED: "LEAD_UPDATED",
//   LEAD_ASSIGNED: "LEAD_ASSIGNED",
//   LEAD_CONVERTED: "LEAD_CONVERTED",

//   CONTACT_CREATED: "CONTACT_CREATED",
//   CONTACT_UPDATED: "CONTACT_UPDATED",

//   COMPANY_CREATED: "COMPANY_CREATED",
//   COMPANY_UPDATED: "COMPANY_UPDATED",

//   DEAL_CREATED: "DEAL_CREATED",
//   DEAL_UPDATED: "DEAL_UPDATED",

//   TASK_CREATED: "TASK_CREATED",
//   TASK_COMPLETED: "TASK_COMPLETED",
// } as const;

// export type ActivityType =
//   (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];

export const ACTIVITY_TYPES = {
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  LEAD_CONVERTED: "LEAD_CONVERTED",

  CONTACT_CREATED: "CONTACT_CREATED",
  CONTACT_UPDATED: "CONTACT_UPDATED",

  COMPANY_CREATED: "COMPANY_CREATED",
  COMPANY_UPDATED: "COMPANY_UPDATED",

  DEAL_CREATED: "DEAL_CREATED",
  DEAL_UPDATED: "DEAL_UPDATED",

  TASK_CREATED: "TASK_CREATED",
  TASK_COMPLETED: "TASK_COMPLETED",
 
} as const;

export type ActivityType =
  (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];