// src/constants/activity-types.ts

export const ACTIVITY_TYPES = {
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_UPDATED: "LEAD_UPDATED",
  LEAD_ASSIGNED: "LEAD_ASSIGNED",
  LEAD_CONVERTED: "LEAD_CONVERTED",

  CONTACT_CREATED: "CONTACT_CREATED",
  CONTACT_UPDATED: "CONTACT_UPDATED",

  COMPANY_CREATED: "COMPANY_CREATED",
  COMPANY_UPDATED: "COMPANY_UPDATED",

  DEAL_CREATED: "DEAL_CREATED",
  DEAL_UPDATED: "DEAL_UPDATED",
  DEAL_MOVED: "DEAL_MOVED",
  DEAL_WON: "DEAL_WON",
  DEAL_LOST: "DEAL_LOST",

  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_COMPLETED: "TASK_COMPLETED",

  USER_INVITED: "USER_INVITED",
  USER_JOINED: "USER_JOINED",

} as const;

export type ActivityType =
  (typeof ACTIVITY_TYPES)[keyof typeof ACTIVITY_TYPES];