import { ROLES } from "./index.js";
import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {

  [ROLES.ADMIN]: [

    ...Object.values(PERMISSIONS),

  ],

  [ROLES.MANAGER]: [

    PERMISSIONS.CREATE_LEAD,
    PERMISSIONS.VIEW_LEAD,
    PERMISSIONS.EDIT_LEAD,

    PERMISSIONS.CREATE_CONTACT,
    PERMISSIONS.VIEW_CONTACT,
    PERMISSIONS.EDIT_CONTACT,

    PERMISSIONS.CREATE_COMPANY,
    PERMISSIONS.VIEW_COMPANY,
    PERMISSIONS.EDIT_COMPANY,

    PERMISSIONS.CREATE_DEAL,
    PERMISSIONS.VIEW_DEAL,
    PERMISSIONS.EDIT_DEAL,

    PERMISSIONS.CREATE_TASK,
    PERMISSIONS.VIEW_TASK,
    PERMISSIONS.EDIT_TASK,

    PERMISSIONS.CREATE_MEETING,
    PERMISSIONS.VIEW_MEETING,
    PERMISSIONS.EDIT_MEETING,

    PERMISSIONS.CREATE_NOTE,
    PERMISSIONS.VIEW_NOTE,

    PERMISSIONS.UPLOAD_DOCUMENT,
    PERMISSIONS.VIEW_DOCUMENT,

    PERMISSIONS.VIEW_REPORTS,

    PERMISSIONS.VIEW_ACTIVITIES,

    PERMISSIONS.VIEW_NOTIFICATIONS,

  ],

  [ROLES.MEMBER]: [

    PERMISSIONS.VIEW_LEAD,

    PERMISSIONS.VIEW_CONTACT,

    PERMISSIONS.VIEW_COMPANY,

    PERMISSIONS.VIEW_DEAL,

    PERMISSIONS.VIEW_TASK,

    PERMISSIONS.VIEW_MEETING,

    PERMISSIONS.CREATE_NOTE,
    PERMISSIONS.VIEW_NOTE,

    PERMISSIONS.VIEW_DOCUMENT,

    PERMISSIONS.VIEW_ACTIVITIES,

    PERMISSIONS.VIEW_NOTIFICATIONS,

  ],

};